goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='catalog'),  # Один каталог для всех категорий
    path('product/', views.product, name='product'),  # Если нужна страница отдельного товара
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('cart/', views.cart, name='cart'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.reviews, name='reviews'),
]

sharofeya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls')),
    path('reviews/', include('reviews.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name='Название товара')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    price = models.DecimalField(verbose_name='Цена',default=0.00, max_digits=7, decimal_places=2 )
    image = models.ImageField(upload_to='products/', verbose_name='Фото', blank=True, null=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    category = models.ForeignKey(verbose_name='Категория', to=Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

reviews/models.py
from django.db import models


class Review(models.Model):
    image = models.ImageField(upload_to='reviews/', verbose_name='Фото отзыва')
    is_active = models.BooleanField(default=True, verbose_name='Активен')

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'
        db_table = 'reviews'

    def __str__(self):
        return f'Отзыв #{self.id}'

goods/views.py
from django.shortcuts import render

# Главная галерея/категории товаров
def catalog(request):
    return render(request, 'goods/catalog.html')

def product(request):
    return render(request, 'goods/product.html')

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

def catalog(request):
    return render(request, 'main/catalog.html')


def contacts(request):
    return render(request, 'main/contacts.html')

def reviews(request):
    return render(request, 'main/reviews.html')

def cart(request):
    return render(request, 'main/cart.html')

reviews/views.py
from django.shortcuts import render
from .models import Review


# reviews/views.py
def reviews(request):
    reviews = Review.objects.filter(is_active=True)
    return render(request, 'reviews/reviews.html', {
        'reviews': reviews
    })

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Base CSS -->
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">

    <!-- Google Font (navbar) -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gravitas+One&display=swap" rel="stylesheet">

    {% block css %}{% endblock css %}

    <title>{% block title %}ШароФея{% endblock %}</title>
</head>

<body>
<main>

    <!-- Navbar -->
    <div class="navbar">
        <h2>ШароФея</h2>
        <ul>
            <li><a href="{% url 'main:index' %}">Главная</a></li>
            <li><a href="{% url 'goods:catalog' %}">Каталог</a></li>
            <li><a href="{% url 'main:contacts' %}">Контакты</a></li>
            <li><a href="{% url 'reviews:reviews' %}">Отзывы</a></li>
            <li><a href="{% url 'main:cart' %}">Корзина</a></li>
        </ul>
    </div>

    {% block content %}{% endblock content %}

    <!-- Modal -->
    <div id="review-modal" class="modal">
        <span class="close">&times;</span>
        <img class="modal-img" id="review-modal-img">
        <p class="modal-text" id="review-modal-text"></p>
    </div>

</main>

{% block footer %}
<footer>
    <div class="start">
        <address>
            <p><a href="mailto:i@innasher.ru">i@innasher.ru</a></p>
            <p>Телефон: <a href="tel:+79255181722">+7-925-518-17-22</a></p>
        </address>

        <address class="start1">
            <a href="https://t.me/feia_mi" target="_blank">
                <img src="https://img.icons8.com/ios/50/telegram.png">
            </a>
            <a href="https://www.instagram.com/feia_mi" target="_blank">
                <img src="https://img.icons8.com/ios/50/instagram-new--v1.png">
            </a>
            <a href="https://vk.ru/feia_mi" target="_blank">
                <img src="https://img.icons8.com/ios/50/vk-com.png">
            </a>
        </address>
    </div>
</footer>
{% endblock footer %}

<script src="{% static 'main/js/index.js' %}"></script>
</body>
</html>

main/templates/main/contacts.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/contacts.css' %}">
{% endblock css %}

    <title>ШароФея</title>
</head>

<body>
    <main>

        <!-- Navbar -->
        <div class="navbar">
            <h2>ШароФея</h2>
            <ul>
                <li><a href="{% url 'index' %}" data-filter="all">Главная</a></li>
                <li><a href="{% url 'catalog' %}" data-filter="catalog">Каталог</a></li>
                <li><a href="{% url 'contacts' %}" data-filter="contacts">Контакты</a></li>
                <li><a href="{% url 'reviews' %}" data-filter="reviews">Отзывы</a></li>
                <li><a href="{% url 'cart' %}" data-filter="cart">Корзина</a></li>
            </ul>
        </div>

{% block content %}
        
    <div class="main-section">
        <div class="wrapper">
            <div class="contact-card">
                <h2>Наши контакты</h2>
                <p>Телефон: <a href="tel:+79001234567" class="telefon">+7-925-518-1722</a></p>
                <a href="mailto:i@innasher.ru?subject=Здравствуйте" class="email-link">i@innasher.ru</a>
                <p>Адрес: г. Москва, ул. Пушкина, д. 10</p>
                <button type="submit">Отправить</button>
            </div>
        </div>

        <section class="contact-form">
            <h2>Свяжитесь с нами</h2>
            <form action="#" method="post">
                <label for="name">Ваше имя:</label>
                <input type="text" id="name" name="name" placeholder="Введите имя" required>

                <label for="email">Email:</label>
                <input type="email" id="email" name="email" placeholder="Введите email" required>

                <label for="message">Сообщение:</label>
                <textarea id="message" name="message" rows="5" placeholder="Ваше сообщение..." required></textarea>

                <button type="submit1">Отправить</button>
            </form>
        </section>
    </div>
{% endblock content %}


    <!-- JS -->
    <script src="{% static 'main/js/index.js' %}"></script>
</body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'main/css/index.css' %}">

<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gravitas+One&amp;family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&amp;display=swap" rel="stylesheet">
{% endblock css %}

<title>ШароФея</title>
</head>

<body>
<main>

    <!-- Navbar -->
    <div class="navbar">
        <h2>ШароФея</h2>
        <ul>
            <li><a href="{% url 'main:index' %}" data-filter="all">Главная</a></li>
            <li><a href="{% url 'goods:catalog' %}" data-filter="catalog">Каталог</a></li>
            <li><a href="{% url 'main:contacts' %}" data-filter="contacts">Контакты</a></li>
            <li><a href="{% url 'reviews:reviews' %}">Отзывы</a></li>
            <li><a href="{% url 'main:cart' %}" data-filter="cart">Корзина</a></li>
        </ul>
    </div>

    <!-- Поиск -->
    <div class="search1">
        <form action="/search" method="get">
            <input type="search" name="q" placeholder="Искать товары...">
            <button type="submit">Найти</button>
        </form>
    </div>

    <!-- Галерея -->
    {% block content %}
    <button class="show-all" data-filter="all">Показать все</button>
    <section class="gallery">
        <h2 class="section-title">Наши оформления</h2>

        <div class="gallery-grid">
            <a href="{% url 'goods:catalog' %}?category=girls" class="gallery-item" data-category="girls">
                <img src="{% static 'main/images/gallery/balloon-01.jpg' %}" alt="Девочкам">
                <span class="overlay-text">Для девочек</span>
            </a>

            <a href="{% url 'goods:catalog' %}?category=boys" class="gallery-item" data-category="boys">
                <img src="{% static 'main/images/gallery/balloon-02.jpg' %}" alt="Мальчикам">
                <span class="overlay-text">Для мальчиков</span>
            </a>

            <a href="{% url 'goods:catalog' %}?category=adults" class="gallery-item" data-category="adults">
                <img src="{% static 'main/images/gallery/balloon-03.jpg' %}" alt="Для взрослых">
                <span class="overlay-text">Для взрослых</span>
            </a>

            <a href="{% url 'goods:catalog' %}?category=extract" class="gallery-item" data-category="extract">
                <img src="{% static 'main/images/gallery/balloon-03.jpg' %}" alt="Выписка">
                <span class="overlay-text">Выписка</span>
            </a>

            <a href="{% url 'goods:catalog' %}?category=balloons" class="gallery-item" data-category="balloons">
                <img src="{% static 'main/images/gallery/balloon-01.jpg' %}" alt="Просто шары">
                <span class="overlay-text">Просто шары</span>
            </a>

            <a href="{% url 'goods:catalog' %}?category=photobooth" class="gallery-item" data-category="photobooth">
                <img src="{% static 'main/images/gallery/balloon-04.jpg' %}" alt="Фотозоны">
                <span class="overlay-text">Фотозоны</span>
            </a>

            <a href="{% url 'goods:catalog' %}?category=other" class="gallery-item" data-category="other">
                <img src="{% static 'main/images/gallery/balloon-04.jpg' %}" alt="Прочее">
                <span class="overlay-text">Прочее</span>
            </a>
        </div>
    </section>
{% endblock content %}


    <!-- Модальное окно для отзывов -->
    <div id="review-modal" class="modal">
        <span class="close">&times;</span>
        <img class="modal-img" id="review-modal-img">
        <p class="modal-text" id="review-modal-text"></p>
    </div>
</main>

<!-- Footer -->
{% block footer %}
<footer>
    <div class="start">
        <address>
            <p><a href="mailto:i@innasher.ru?subject=Здравствуйте" class="email-link">i@innasher.ru</a></p>
            <p>Телефон: <a href="tel:+79001234567">+7-925-518-1722</a></p>
        </address>
        <address class="start1">
            <a href="https://t.me/feia_mi" target="_blank">
                <img width="50" height="50" src="https://img.icons8.com/ios/50/telegram.png" alt="Telegram" />
            </a>
            <a href="https://www.instagram.com/feia_mi" target="_blank">
                <img width="50" height="50" src="https://img.icons8.com/ios/50/instagram-new--v1.png" alt="Instagram" />
            </a>
            <a href="https://vk.ru/feia_mi" target="_blank">
                <img width="50" height="50" src="https://img.icons8.com/ios/50/vk-com.png" alt="VK" />
            </a>
        </address>
    </div>
</footer>
{% endblock footer %}

<!-- JS -->
<script src="{% static 'main/js/index.js' %}"></script>
</body>
</html>

reviews/templates/reviews/reviews.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Отзывы{% endblock %}

{# Подключаем CSS именно для этой страницы #}
{% block css %}
<link rel="stylesheet" href="{% static 'main/css/reviews.css' %}">
{% endblock css %}

{% block content %}
<section class="reviews">
    <h2 class="section-title">Отзывы клиентов</h2>

    <div class="reviews-grid">
        {% for review in reviews %}
            <article class="review-card">
                <img src="{{ review.image.url }}" alt="Отзыв клиента">
            </article>
        {% empty %}
            <p class="empty">Отзывов пока нет</p>
        {% endfor %}
    </div>
</section>
{% endblock content %}

{% block js %}
<script src="{% static 'main/js/index.js' %}"></script>
{% endblock js %}